# Generated by Django 4.2 on 2023-04-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_date_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='default', unique=True),
        ),
    ]
