# Generated by Django 4.2 on 2023-05-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
