# Generated by Django 4.2 on 2023-04-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='shop',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
