# Generated by Django 4.2 on 2023-05-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
